# Generated by Django 4.0.1 on 2022-08-29 16:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='暱稱')),
                ('gender', models.CharField(choices=[('1', '男性'), ('2', '女性')], default='1', max_length=1, verbose_name='性別')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='電子信箱')),
                ('password', models.CharField(max_length=20, verbose_name='密碼')),
                ('image', models.CharField(choices=[('monster-1.png', 'Monster1'), ('monster-2.png', 'Monster2'), ('monster-3.png', 'Monster3'), ('monster-4.png', 'Monster4'), ('monster-5.png', 'Monster5'), ('monster-6.png', 'Monster6')], max_length=20, verbose_name='頭像')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=20, verbose_name='話題')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='編輯器內文')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '貼文',
                'verbose_name_plural': '貼文',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='話題')),
                ('post_number', models.IntegerField(default=0, verbose_name='發文數')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '話題',
                'verbose_name_plural': '話題',
                'ordering': ['-id'],
            },
        ),
    ]
