# Generated by Django 4.0.1 on 2022-08-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['update_date'], 'verbose_name': '貼文', 'verbose_name_plural': '貼文'},
        ),
        migrations.AddField(
            model_name='post',
            name='topic_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.topic'),
        ),
    ]
