# Generated by Django 4.0.1 on 2022-09-16 14:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '話題', 'verbose_name_plural': '話題'},
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.CharField(choices=[('monster-1.png', '咘咘'), ('monster-2.png', '喬治'), ('monster-3.png', '布萊恩'), ('monster-4.png', '里歐'), ('monster-5.png', '鮑伯'), ('monster-6.png', '艾倫')], max_length=20, verbose_name='頭像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100, verbose_name='編輯器內文'),
        ),
    ]
