# Generated by Django 4.0.1 on 2022-09-24 16:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_alter_topic_options_alter_members_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='編輯器內文'),
        ),
    ]
