# Generated by Django 4.0.1 on 2022-10-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='times',
            field=models.IntegerField(default=0, verbose_name='出現次數'),
        ),
    ]
