# Generated by Django 4.0.1 on 2022-10-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0008_topic_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='搜尋連結'),
        ),
    ]
