# Generated by Django 4.0.1 on 2022-11-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0010_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-times'], 'verbose_name': '話題', 'verbose_name_plural': '話題'},
        ),
    ]
